### ISSUE TITLE
Better Explanation

### ISSUE THREAD

**Issue by xamino** [kingsongunlocker/kingsongunlocker.github.io#2]
Either include a text explanation on the website where the code can be found, or alternatively add a new first field which takes the bluetooth mac address and reverses it for you.

**Comment by xamino** [comment]
Implemented as of https://github.com/kingsongunlocker/kingsongunlocker.github.io/commit/37ee3af0ee5c74b4b0faad0454afd7e2b88789c5 .

**Comment by AgentFire** [comment]
I would still require additional info regarding on how to get Bluetooth MAC as it does not show in the app.

**Comment by xamino** [comment]
True for the new app. IIRC the old app shows a listing of nearby wheels, with the Bluetooth MAC displayed beneath it. That would be one possibility to get the MAC. Ridiculously you otherwise need an [app](https://play.google.com/store/apps/details?id=com.ccpcreations.android.bluetoothmacfinder&hl=en) to get a list (no clue if it works, I googled it). Hope I could help!
